var RAISIO = RAISIO || {};

RAISIO.data = [
    {
        "cow": "KooNee",
        "calving": 2,
        "dim": 297,
        "milkings": 3,
        "feeding": 2.88,
        "actual": 30.7,
        "expected": 29.3,
        "difference": 1.4,
        "performance": ""
    },
    {
        "cow": "Kapina",
        "calving": 2,
        "dim": 151,
        "milkings": 1.6,
        "feeding": 2.11,
        "actual": 18.5,
        "expected": 19.1,
        "difference": -0.6,
        "performance": ""
    },
    {
        "cow": "Kiva",
        "calving": 3,
        "dim": 192,
        "milkings": 3.1,
        "feeding": 4.21,
        "actual": 31.5,
        "expected": 30.9,
        "difference": 0.6,
        "performance": ""
    },
    {
        "cow": "Kaunis",
        "calving": 3,
        "dim": 253,
        "milkings": 3.1,
        "feeding": 8.61,
        "actual": 47.3,
        "expected": 42.3,
        "difference": 5,
        "performance": ""
    },
    {
        "cow": "Kaipaus",
        "calving": 2,
        "dim": 36,
        "milkings": 3,
        "feeding": 7.94,
        "actual": 56.1,
        "expected": 55.8,
        "difference": 0.3,
        "performance": ""
    },
    {
        "cow": "Karita",
        "calving": 2,
        "dim": 62,
        "milkings": 3.3,
        "feeding": 6.69,
        "actual": 45.2,
        "expected": 42.6,
        "difference": 2.6,
        "performance": ""
    },
    {
        "cow": "Kapri",
        "calving": 3,
        "dim": 236,
        "milkings": 3.1,
        "feeding": 3.92,
        "actual": 21.8,
        "expected": 32.1,
        "difference": -10.3,
        "performance": "Underperformer"
    },
    {
        "cow": "Krista",
        "calving": 2,
        "dim": 227,
        "milkings": 1.7,
        "feeding": 3.29,
        "actual": 22.3,
        "expected": 26,
        "difference": -3.7,
        "performance": ""
    },
    {
        "cow": "Lahja",
        "calving": 4,
        "dim": 80,
        "milkings": 4,
        "feeding": 5.05,
        "actual": 37.9,
        "expected": 37.5,
        "difference": 0.4,
        "performance": ""
    },
    {
        "cow": "Louhi",
        "calving": 1,
        "dim": 224,
        "milkings": 3.1,
        "feeding": 11.17,
        "actual": 31.5,
        "expected": 32.4,
        "difference": -0.9,
        "performance": ""
    },
    {
        "cow": "Leia",
        "calving": 1,
        "dim": 144,
        "milkings": 2,
        "feeding": 3.7,
        "actual": 13.7,
        "expected": 34.5,
        "difference": -20.8,
        "performance": "Underperformer"
    },
    {
        "cow": "Lady",
        "calving": 3,
        "dim": 255,
        "milkings": 1.6,
        "feeding": 0,
        "actual": 23.5,
        "expected": 21.4,
        "difference": 2.1,
        "performance": ""
    },
    {
        "cow": "Lumikki",
        "calving": 3,
        "dim": 128,
        "milkings": 3.1,
        "feeding": 6.77,
        "actual": 62.5,
        "expected": 58.8,
        "difference": 3.7,
        "performance": ""
    },
    {
        "cow": "Linnea",
        "calving": 2,
        "dim": 256,
        "milkings": 3.6,
        "feeding": 10.08,
        "actual": 38.4,
        "expected": 35.7,
        "difference": 2.7,
        "performance": ""
    },
    {
        "cow": "Lola",
        "calving": 2,
        "dim": 274,
        "milkings": 3.3,
        "feeding": 3.83,
        "actual": 32.9,
        "expected": 34.4,
        "difference": -1.5,
        "performance": ""
    },
    {
        "cow": "Leeti",
        "calving": 2,
        "dim": 178,
        "milkings": 1.7,
        "feeding": 3.53,
        "actual": 34,
        "expected": 34.7,
        "difference": -0.7,
        "performance": ""
    },
    {
        "cow": "Joulunsydän",
        "calving": 5,
        "dim": 257,
        "milkings": 2.3,
        "feeding": 4.49,
        "actual": 30.1,
        "expected": 32.4,
        "difference": -2.3,
        "performance": ""
    },
    {
        "cow": "Jouluntaika",
        "calving": 1,
        "dim": 15,
        "milkings": 2,
        "feeding": 5.95,
        "actual": 28.1,
        "expected": 29.9,
        "difference": -1.8,
        "performance": ""
    },
    {
        "cow": "Kivi",
        "calving": 1,
        "dim": 175,
        "milkings": 3.3,
        "feeding": 3.75,
        "actual": 37.2,
        "expected": 36.8,
        "difference": 0.4,
        "performance": ""
    },
    {
        "cow": "Milja",
        "calving": 4,
        "dim": 110,
        "milkings": 2.7,
        "feeding": 3.09,
        "actual": 44.5,
        "expected": 33.3,
        "difference": 11.2,
        "performance": "OverPerformer"
    },
    {
        "cow": "Hilja",
        "calving": 1,
        "dim": 269,
        "milkings": 2,
        "feeding": 3.48,
        "actual": 21.6,
        "expected": 21.6,
        "difference": 0,
        "performance": ""
    },
    {
        "cow": "Silja",
        "calving": 2,
        "dim": 265,
        "milkings": 3.1,
        "feeding": 10.54,
        "actual": 32.8,
        "expected": 30.5,
        "difference": 2.3,
        "performance": ""
    },
    {
        "cow": "Kiilto",
        "calving": 2,
        "dim": 36,
        "milkings": 2.6,
        "feeding": 5.77,
        "actual": 41.7,
        "expected": 39.2,
        "difference": 2.5,
        "performance": ""
    },
    {
        "cow": "Kilta",
        "calving": 4,
        "dim": 10,
        "milkings": 3.7,
        "feeding": 4.63,
        "actual": 27.9,
        "expected": 31.8,
        "difference": -3.9,
        "performance": ""
    },
    {
        "cow": "Kulta",
        "calving": 2,
        "dim": 86,
        "milkings": 3.7,
        "feeding": 7.09,
        "actual": 53.8,
        "expected": 51,
        "difference": 2.8,
        "performance": ""
    },
    {
        "cow": "Vilja",
        "calving": 1,
        "dim": 166,
        "milkings": 3.6,
        "feeding": 7.76,
        "actual": 20.6,
        "expected": 28.4,
        "difference": -7.8,
        "performance": "Underperformer"
    },
    {
        "cow": "Karma",
        "calving": 1,
        "dim": 221,
        "milkings": 3.3,
        "feeding": 2.86,
        "actual": 27.5,
        "expected": 28,
        "difference": -0.5,
        "performance": ""
    },
    {
        "cow": "Libya",
        "calving": 2,
        "dim": 83,
        "milkings": 3.4,
        "feeding": 6.56,
        "actual": 40.6,
        "expected": 44.1,
        "difference": -3.5,
        "performance": ""
    },
    {
        "cow": "Lopunalku",
        "calving": 3,
        "dim": 22,
        "milkings": 2.3,
        "feeding": 6.03,
        "actual": 40,
        "expected": 28,
        "difference": 12,
        "performance": "OverPerformer"
    },
    {
        "cow": "Lambada",
        "calving": 2,
        "dim": 277,
        "milkings": 2.1,
        "feeding": 2.41,
        "actual": 29.1,
        "expected": 31,
        "difference": -1.9,
        "performance": ""
    },
    {
        "cow": "Lilatsu",
        "calving": 1,
        "dim": 101,
        "milkings": 2.9,
        "feeding": 4.16,
        "actual": 28.1,
        "expected": 29,
        "difference": -0.9,
        "performance": ""
    },
    {
        "cow": "Limikkikukka",
        "calving": 2,
        "dim": 285,
        "milkings": 2.3,
        "feeding": 4.63,
        "actual": 29.9,
        "expected": 31.7,
        "difference": -1.8,
        "performance": ""
    },
    {
        "cow": "Lisie",
        "calving": 5,
        "dim": 49,
        "milkings": 2,
        "feeding": 5.13,
        "actual": 35.3,
        "expected": 36.2,
        "difference": -0.9,
        "performance": ""
    },
    {
        "cow": "Hipsu",
        "calving": 2,
        "dim": 254,
        "milkings": 2.3,
        "feeding": 8.4,
        "actual": 34.2,
        "expected": 32,
        "difference": 2.2,
        "performance": ""
    },
    {
        "cow": "Hertta",
        "calving": 6,
        "dim": 239,
        "milkings": 2.3,
        "feeding": 3.17,
        "actual": 25.2,
        "expected": 26.4,
        "difference": -1.2,
        "performance": ""
    }
];